// Code written by Gabriel Mailhot, 11/13/2022.

namespace TalesEnums
{
    public enum Occupation
    {
        Notassigned = -1,
        Tavernkeeper = 0,
        Mercenary = 1,
        Lord = 2,
        Lady = 3,
        Goodstrader = 4,
        Arenamaster = 5,
        Companion = 6,
        Villager = 7,
        Soldier = 8,
        Townsfolk = 9,
        Guildmaster = 10,
        Marshall = 11,
        Tournamentfixer = 12,
        Ransombroker = 13,
        Weaponsmith = 14,
        Armorer = 15,
        Horsetrader = 16,
        Tavernwench = 17,
        Shopkeeper = 18,
        Taverngamehost = 19,
        Bandit = 20,
        Wanderer = 21,
        Artisan = 22,
        Merchant = 23,
        Preacher = 24,
        Headman = 25,
        Gangleader = 26,
        Ruralnotable = 27,
        Outlaw = 28,
        Minorfactioncharacter = 29,
        Prisonguard = 30,
        Guard = 31,
        Shopworker = 32,
        Musician = 33,
        Gangster = 34,
        Blacksmith = 35,
        Judge = 36,
        Bannerbearer = 37,
        Caravanguard = 38,
        Special = 39,
        Numberofoccupations = 40
    }
}